### PR TITLE
fix: add rlock() for fqdnToEntry map

### LINKED ISSUE #210: fatal error: concurrent map iteration and map write
### Description

```
{"time":"2026-02-18T09:38:08.010050933+01:00","level":"INFO","msg":"started processing request","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.8","Port":43512,"Zone":""},"req-id":14427,"logger":"DNS proxy/DNS handler","server":{"IP":"192.168.1.1","Port":53,"Zone":""},"bufsize":512,"request":{"Id":14427,"Response":false,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":false,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":null,"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.011276217+01:00","level":"INFO","msg":"started processing request","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.4","Port":55673,"Zone":""},"req-id":62240,"logger":"DNS proxy/DNS handler","server":{"IP":"192.168.1.1","Port":53,"Zone":""},"bufsize":512,"request":{"Id":62240,"Response":false,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":false,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":null,"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.01449001+01:00","level":"INFO","msg":"started processing request","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.4","Port":35665,"Zone":""},"req-id":28452,"logger":"DNS proxy/DNS handler","server":{"IP":"192.168.1.1","Port":53,"Zone":""},"bufsize":512,"request":{"Id":28452,"Response":false,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":false,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":null,"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.024080507+01:00","level":"INFO","msg":"started processing request","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.8","Port":34385,"Zone":""},"req-id":55595,"logger":"DNS proxy/DNS handler","server":{"IP":"192.168.1.1","Port":53,"Zone":""},"bufsize":512,"request":{"Id":55595,"Response":false,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":false,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":null,"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.031530305+01:00","level":"INFO","msg":"processing response","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.8","Port":43512,"Zone":""},"req-id":14427,"logger":"DNS proxy/DNS handler","buffer size":512,"original response":{"Id":14427,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2889,"Rdlength":4},"A":"192.168.1.1"}],"Ns":[],"Extra":[]},"truncated response":{"Id":14427,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2889,"Rdlength":4},"A":"192.168.1.1"}],"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.032015613+01:00","level":"INFO","msg":"processing response","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.4","Port":55673,"Zone":""},"req-id":62240,"logger":"DNS proxy/DNS handler","buffer size":512,"original response":{"Id":62240,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2786,"Rdlength":4},"A":"192.168.1.1"}],"Ns":[],"Extra":[]},"truncated response":{"Id":62240,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2786,"Rdlength":4},"A":"192.168.1.1"}],"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.036868362+01:00","level":"INFO","msg":"processing response","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.4","Port":35665,"Zone":""},"req-id":28452,"logger":"DNS proxy/DNS handler","buffer size":512,"original response":{"Id":28452,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2120,"Rdlength":4},"A":"192.168.1.1"}],"Ns":[],"Extra":[]},"truncated response":{"Id":28452,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2120,"Rdlength":4},"A":"192.168.1.1"}],"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.036868362+01:00","level":"INFO","msg":"processing response","query":"xxx.example.com.","client-addr":{"IP":"10.88.64.4","Port":35665,"Zone":""},"req-id":28452,"logger":"DNS proxy/DNS handler","buffer size":512,"original response":{"Id":28452,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2120,"Rdlength":4},"A":"192.168.1.1"}],"Ns":[],"Extra":[]},"truncated response":{"Id":28452,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":0,"Question":[{"Name":"xxx.example.com.","Qtype":1,"Qclass":1}],"Answer":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2120,"Rdlength":4},"A":"192.168.1.1"}],"Ns":null,"Extra":null}}
{"time":"2026-02-18T09:38:08.037031866+01:00","level":"INFO","msg":"updating ip entry","fqdn":"xxx.example.com.","ip_len":1,"dtype":"ipv4_addr","set":"ad09cad146599faa","lookupTime":"2026-02-18T09:38:08.036910209+01:00","rrs":[{"Hdr":{"Name":"xxx.example.com.","Rrtype":1,"Class":1,"Ttl":2120,"Rdlength":4},"A":"192.168.1.1"}],"logger":"DNS proxy/DNS cache"}
fatal error: {"time":"2026-02-18T09:38:08.037049788+01:00","level":"INFO","msg":"added new IP entry","fqdn":"xxx.example.com.","ip_len":1,"dtype":"ipv4_addr","set":"ad09cad146599faa","logger":"DNS proxy/DNS cache"}
concurrent map iteration and map write
goroutine 596 [running]:
internal/runtime/maps.fatal({0x1d39c2c?, 0x47ed13?})
        runtime/panic.go:1046 +0x18
internal/runtime/maps.(*Iter).Next(0xc015c70b00?)
        internal/runtime/maps/table.go:792 +0x86
reflect.mapIterNext(0x1b23f00?)
        reflect/map_swiss.go:203 +0x13
reflect.(*MapIter).Next(0xc00053d840)
        reflect/map_swiss.go:358 +0x3e
encoding/json.mapEncoder.encode({0x17a7b4a?}, 0xc000942d00, {0x1ab2460?, 0xc003976ab0?, 0x1ab2460?}, {0x58?, 0x17?})
        encoding/json/encode.go:799 +0x329
encoding/json.(*encodeState).reflectValue(0xc000942d00, {0x1ab2460?, 0xc003976ab0?, 0x45e62e?}, {0x40?, 0x6b?})
        encoding/json/encode.go:367 +0x73
encoding/json.(*encodeState).marshal(0xc0006c40c0?, {0x1ab2460?, 0xc003976ab0?}, {0x84?, 0x5c?})
        encoding/json/encode.go:343 +0xb2
encoding/json.Marshal({0x1ab2460, 0xc003976ab0})
        encoding/json/encode.go:209 +0xbe
sigs.k8s.io/yaml.Marshal({0x1ab2460?, 0xc003976ab0?})
        sigs.k8s.io/yaml@v1.4.0/yaml.go:32 +0x1d
github.com/metal-stack/firewall-controller/v2/pkg/dns.(*DNSCache).writeStateToConfigmap(0xc000065c80)
        github.com/metal-stack/firewall-controller/v2/pkg/dns/dnscache.go:172 +0x4d
github.com/metal-stack/firewall-controller/v2/pkg/dns.(*DNSCache).Update(0xc000065c80, {0x44?, 0xc002028980?, 0x2eda3e0?}, {0xc015ca2090, 0x14}, 0xc015c847e0, {0x0, 0x0, 0x0})
        github.com/metal-stack/firewall-controller/v2/pkg/dns/dnscache.go:455 +0x1a15
github.com/metal-stack/firewall-controller/v2/pkg/dns.NewDNSProxyHandler.getUpdateCacheFunc.func1({0x65776f6c6c417075?, 0x736c6166203a2264?, 0x2eda3e0?}, 0xc015c847e0)
        github.com/metal-stack/firewall-controller/v2/pkg/dns/dns_proxy_handler.go:148 +0x2a5
created by github.com/metal-stack/firewall-controller/v2/pkg/dns.(*DNSProxyHandler).ServeDNS in goroutine 524
        github.com/metal-stack/firewall-controller/v2/pkg/dns/dns_proxy_handler.go:81 +0x7a6

```

### PR DESCRIPTION
**Pull request by mwennrich**
closes: https://github.com/metal-stack/firewall-controller/issues/210

## Description

None

### CODE REVIEW

File: pkg/dns/dnscache.go [hunk 1]
```diff
@@ -169,7 +169,9 @@ func newDNSCache(ctx context.Context, dns string, ipv4Enabled, ipv6Enabled bool,
 
 // writeStateToConfigmap writes the whole DNS cache to the state configmap
 func (c *DNSCache) writeStateToConfigmap() error {
+	c.RLock()
 	s, err := yaml.Marshal(c.fqdnToEntry)
+	c.RUnlock()
```
Comment (majst01) [inline pkg/dns/dnscache.go:174]: at the first glance i thought it would be better to have the unlock also in a defer statement right after the lock, but as there is a lot of logic going on later and the map is only read here, this is fine.

**Review by majst01 — APPROVED** [review]
